apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::134852783623:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-XPX0VCU0DRG5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::134852783623:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-10T20:16:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "933"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e378e02a-87fa-4f17-beaa-208cadd041dc
